# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  push:
    tags:
      - v**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: 'Unser_Server_Modpack.mrpack'
          directory: ${{ github.workspace }}/packfiles

      - name: Attach file to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: ${{ github.workspace }}/packfiles/Unser_Server_Modpack.mrpack
